## Anaconda
- 파이썬 통합 개발환경(IDE)
- jupyter notebook 지원
- https://www.anaconda.com/products/individual

## Jupyter notebook
- Windows Powershell (shift+우클릭) / 명령 프롬프트(cmd) / Mac OS X terminal
 실행
- jupyter notebook 입력
- H: 키보드 단축키 설명

## 데이터 처리 및 분석을 위한 파이썬 모듈

1. Numpy: 다차원 배열 생성 및 연산
2. Pandas: Dataframe 생성 및 조작
3. Scipy: 과학 및 공학 연산 --> 통계분석
4. Matplotlib: 시각화


In [ ]:
#  모듈설치

### Windows 명령 프롬프트(cmd), Powershell 
#pip install numpy scipy pandas matplotlib --user
### Mac OS 터미널
#pip3 install numpy scipy pandas matplotlib
### Jupyter notebook
#!pip install numpy scipy pandas matplotlib


# Numpy
Numerical Python<br/><br/>
다차원 배열(multi-dimensional array)을 쉽고 빠르게 처리<br/>
숫자로 이루어진 Table형 데이터를 다룰 때 주로 사용<br/>
같은 종류의 data type을 원소로 함<br/>

https://wikidocs.net/14569


In [ ]:
import numpy as np

In [ ]:
tmp = [j for j in range(10)]
tmp1 = []
for i in range(len(tmp)):
    if i>3:
        tmp1.append(i)
tmp1

[4, 5, 6, 7, 8, 9]

In [ ]:
xx = np.array(tmp)
list(xx[xx>3])

[4, 5, 6, 7, 8, 9]

###차원에 따라 데이터를 부르는 이름
- 1차원: vector<br/>
- 2차원: matrix<br/>
- 3차원: tensor


# Ndarray (N-dimensional Array) <b/>
- numpy를 통해 생성되는 n차원의 배열 객체
- 같은 data type만을 담을 수 있음
- 배열과 배열 간에 다양항 수학적 연산 가능


# 리스트와 어레이의 차이점
1. 선언 조건
- 리스트 : 숫자형, 문자열 등 모든 자료 타입 보존 가능
- 넘파이 배열 : 한 가지 자료형만 허용

2. 연산
- 리스트 : 덧셈 시 항목을 이어붙이는 concatenate 수행, 리스트 간의 다른 연산 허용X
- 넘파이 배열 : 덧셈 시 항목 간 덧셈을 수행 , 실수에 대한 사칙연산 과정 수행 가능 

3. 메소드
- 자료형의 종류가 다르기 지원하는 메소드의 종류가 다름 
(EX) 리스트에서는 mean, argmax, round 등 어레이 메소드 지원X

4. 연산 속도
- 같은 연산을 수행하는 경우 넘파이 배열이 연산 최적화가 더 잘되어 있음

# ndarray 생성 함수
- numpy.arange:np.arange([start,] stop[, step,], dtype=None)
- numpy.linspace: numpy.linspace(start, stop, [num=50, endpoint=True, retstep=False, dtype=None)])
- numpy.logspace: log scale

In [ ]:
#array 함수의 인수에 리스트를 지정하여 배열 형성 
# numpy.array(object, [dtype=None, copy=True, order=None, subok=False, ndmin=0])
# 추가 키워드 인자 사용 가능

In [ ]:
import numpy as np
a = [1,2,3,4,5]
print(a, type(a))
b= np.array(a)
print(b, type(b))

[1, 2, 3, 4, 5] <class 'list'>
[1 2 3 4 5] <class 'numpy.ndarray'>


In [ ]:
b_list=b.tolist()
print(type(b_list))

<class 'list'>


In [ ]:
c = [[1,2,3,4,5],[6,7,8,9,10]]
print(c, type(c))
d = np.array(c)
print(d, type(d))

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]] <class 'list'>
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]] <class 'numpy.ndarray'>


In [ ]:
print(d)
print(d[1,2])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
8


In [ ]:
# size: 총 원소의 개수
# shape: 차원구조
# ndim : 차원 수
# dtype: 원소의 data type

a = "abcd"
b = list(a)
c = tuple(a)
d = dict((('a',1), ('b',2)))
e = set(a)

print(a, np.array(a).size, np.array(a).shape, np.array(a).ndim, np.array(a).dtype)
print(b, np.array(b).size, np.array(b).shape, np.array(b).ndim, np.array(b).dtype)
print(c, np.array(c).size, np.array(c).shape, np.array(c).ndim, np.array(c).dtype)
print(d, np.array(d).size, np.array(d).shape, np.array(d).ndim, np.array(d).dtype)
print(e, np.array(e).size, np.array(e).shape, np.array(e).ndim, np.array(e).dtype)

abcd 1 () 0 <U4
['a', 'b', 'c', 'd'] 4 (4,) 1 <U1
('a', 'b', 'c', 'd') 4 (4,) 1 <U1
{'a': 1, 'b': 2} 1 () 0 object
{'d', 'a', 'c', 'b'} 1 () 0 object


In [ ]:
a = np.arange(10)
b = np.arange(1,10.)
c = np.arange(1,10,0.5)
d = np.arange(1,10,3,dtype='float')

print(a)
print(b)
print(c)
print(d)

[0 1 2 3 4 5 6 7 8 9]
[1. 2. 3. 4. 5. 6. 7. 8. 9.]
[1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5 9.  9.5]
[1. 4. 7.]


In [ ]:
a = np.linspace(1,10)
b = np.linspace(1,np.pi,num=5) #num 디폴트 값 = 50
c = np.linspace(1,10, num=5, endpoint = False) #stop 표시X
d = np.linspace(1, 10., num=5, retstep=True)    # step 명시
print(a)
print(b)
print(c)
print(d)

[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]
[1.         1.53539816 2.07079633 2.60619449 3.14159265]
[1.  2.8 4.6 6.4 8.2]
(array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ]), 2.25)


In [ ]:
print(np.linspace(2, 4, 3))
print(np.logspace(2, 4, 3))
print(np.log10(100),np.log10(1000),np.log10(10000))

[2. 3. 4.]
[  100.  1000. 10000.]
2.0 3.0 4.0


In [ ]:
a = np.ones((2,5)) #default dtype = float
b = np.zeros((2,5),dtype='int') #default dtype = float
c = np.full((2,3), 0.5)
d = np.eye(3, 5)   
e = np.identity(3)  # 3 by 3 단위행렬 (identity)

print(a)
print(b)
print(c)
print(d)
print(e)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0 0 0 0 0]
 [0 0 0 0 0]]
[[0.5 0.5 0.5]
 [0.5 0.5 0.5]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)
b = a.T
print(b)
c = a.reshape(2,6)
print(c)
d = a.astype(float)
print(d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]


In [ ]:
a = np.arange(9)
a.reshape(1, -1)

b = a.reshape((1,1,9))
c = a.reshape((1,9,1))
d = a.reshape((9,1,1))

print(a)
print(b)
print(c)
print(d)

[0 1 2 3 4 5 6 7 8]
[[[0 1 2 3 4 5 6 7 8]]]
[[[0]
  [1]
  [2]
  [3]
  [4]
  [5]
  [6]
  [7]
  [8]]]
[[[0]]

 [[1]]

 [[2]]

 [[3]]

 [[4]]

 [[5]]

 [[6]]

 [[7]]

 [[8]]]


In [ ]:
a = np.full((2,4),5)
#a + [2]
#a - [1,2,3,4]
#a * ([2],[3])
#a / [a+1]
#a % [1,2,3,4]
#a.tolist() + [1,2,3]
#aa = np.arange(10).reshape(2,5)
#bb = np.arange(10).reshape(5,2)
#aa@bb
#np.dot(aa,bb)

array([[ 60,  70],
       [160, 195]])

In [ ]:
a=np.arange(1,8)
print(a[1:6])
print(a[1:6:2])
print(a[6:1:-1])
print(a)

[2 3 4 5 6]
[2 4 6]
[7 6 5 4 3]
[1 2 3 4 5 6 7]


In [ ]:
#변수[행 슬라이싱, 열 슬라이싱]
a=np.arange(1,13).reshape(3,4)
print(a)
print(a[0:2, 1:3])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[2 3]
 [6 7]]


In [ ]:
x=np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.random.seed(0); np.random.shuffle(x)
x

array([2, 8, 4, 9, 1, 6, 7, 3, 0, 5])

In [ ]:
np.random.seed(0); np.random.shuffle(x)
x

array([4, 0, 1, 5, 8, 7, 3, 9, 2, 6])

In [ ]:
np.random.seed(0); np.random.shuffle(x)
x

array([1, 2, 8, 6, 0, 3, 9, 5, 4, 7])

In [ ]:
np.random.seed(0); np.random.shuffle(x)
x

array([8, 4, 0, 7, 2, 9, 5, 6, 1, 3])

In [ ]:
np.random.seed(0); np.random.shuffle(x)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.random.seed(0); np.random.shuffle(x)
x

array([2, 8, 4, 9, 1, 6, 7, 3, 0, 5])

In [ ]:
np.random.seed(0); np.random.rand(5)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [ ]:
np.random.seed(0); np.random.rand(5)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [ ]:
np.random.seed(5); np.random.rand(5)

array([0.22199317, 0.87073231, 0.20671916, 0.91861091, 0.48841119])

In [ ]:
x=np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.cumsum(x)

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45])

In [ ]:
np.cumprod(x)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
np.diff(np.cumsum(x))

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a1=np.arange(1,5).reshape(2,2)
a2=a1.ravel()
a3=a1.flatten()    # 원본(a1) 값을 바꾸지 않는다
a4=a1.reshape(-1)
print(a1,'\n')
print(a2,'\n')
print(a3,'\n')
print(a4)

[[1 2]
 [3 4]] 

[1 2 3 4] 

[1 2 3 4] 

[1 2 3 4]


In [ ]:
a1[0][0] = 0
print(a1,'\n')
print(a2,'\n')
print(a3,'\n')
print(a4)

[[0 2]
 [3 4]] 

[0 2 3 4] 

[1 2 3 4] 

[0 2 3 4]


In [ ]:
a1 = np.array([[1,2],[3,4]])
a2 = np.array([[5,6],[7,8]])
print(np.concatenate((a1,a2), axis=0), '\n')
print(np.concatenate((a1,a2), axis=1))

[[1 2]
 [3 4]
 [5 6]
 [7 8]] 

[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
a1=np.array([[1,2],[3,4]])
print(a1)
print(a1.repeat(2))

[[1 2]
 [3 4]]
[1 1 2 2 3 3 4 4]


In [ ]:
a1=np.array([[1,2],[3,4]])
print(np.tile(a1,2),'\n')
print(np.tile(a1,(2,3)))

[[1 2 1 2]
 [3 4 3 4]] 

[[1 2 1 2 1 2]
 [3 4 3 4 3 4]
 [1 2 1 2 1 2]
 [3 4 3 4 3 4]]


In [ ]:
a1=np.array([[1,2],[3,4]])
a2=np.array([[5,6],[7,8]])
print(np.append(a1, a2))

[1 2 3 4 5 6 7 8]


In [ ]:
a=np.array([[2,1,6],[0,7,4],[5,3,2]])
#np.sort(a, axis=1)
#np.sort(a, axis=1)[::,::-1]
#np.sort(a, axis=0)
#np.sort(a, axis=0)[::-1]

In [ ]:
np.argsort(a)

array([[1, 0, 2],
       [0, 2, 1],
       [2, 1, 0]])

In [ ]:
a.argsort()

array([[1, 0, 2],
       [0, 2, 1],
       [2, 1, 0]])

In [ ]:
print(np.amin(a), a.min())    # 최솟값
print(np.amax(a), a.max())    # 최댓값
print(np.argmin(a), a.argmin())    # 최솟값 index
print(np.argmax(a), a.argmax())    # 최댓값 index

0 0
7 7
3 3
4 4


In [ ]:
# 연립방정식 해 구하기

# x+2y=5 2x+3y=8
A = np.linalg.inv(np.array([[1,2],[2,3]]))    # np.linalg.inv: 역행렬
B = np.array([5,8])
C = np.dot(A,B); C    # np.dot : 행렬의 곱(내적)

array([1., 2.])

In [ ]:
a = np.random.rand(3,2)
print(a)

[[0.7384403  0.44130922]
 [0.15830987 0.87993703]
 [0.27408646 0.41423502]]


In [ ]:
np.savetxt('out.txt', a, fmt='%.4f', delimiter='\t')
np.loadtxt('out.txt', dtype='float', delimiter='\t')

array([[0.7384, 0.4413],
       [0.1583, 0.8799],
       [0.2741, 0.4142]])