In [1]:
# installing yfinance
!pip install yfinance seaborn

In [2]:
import numpy as np 
import pandas as pd 
import yfinance as yf    # yahoo finance 주가
from scipy import stats    
import matplotlib.pyplot as plt 
import seaborn as sns     # 시각화
from sklearn import preprocessing

## Pandas

Pandas는 크게 2개로 나뉜다  
1. Series
- 1차원 데이터
- indexing 요소가 추가된 list 혹은 dict와 유사
- DataFrame 내에서 하나의 column이 됨

2. DataFrame
- 2차원 표의 형태

# Series

In [3]:
S = pd.Series([11, 28, 82, 3, 6, 8])
S
#print(type(S))
#print(len(S))

0    11
1    28
2    82
3     3
4     6
5     8
dtype: int64

In [4]:
S.index # index 층

RangeIndex(start=0, stop=6, step=1)

In [5]:
S.values # valeus 층

array([11, 28, 82,  3,  6,  8], dtype=int64)

In [6]:
#pd.Series(list('abc'))   # list
#pd.Series((1,2,3,4,5))   # tuple
#pd.Series({'a':2, 'b':4})  # dict : key값 = index 층
#pd.Series(np.array([1,2.,1]))   # ndarray
#pd.Series(np.arange(4).reshape(2,2))  # 2차원 이상 불가

In [7]:
S=pd.Series([11,28,82,3,6,8],
            ['1st','2nd','3rd','4th','5th','6th'])
#print(S[0::2])

In [8]:
# Series indexing, slicing
#S[1]
#S[0]
#S[0:2]
#S[2:4]

In [9]:
# Tesla 종가 Series
Close = [300, 304, 292, 302, 303]
idx = pd.date_range('20230314', periods=5)
Tesla = pd.Series(Close, index=idx)
Tesla

2023-03-14    300
2023-03-15    304
2023-03-16    292
2023-03-17    302
2023-03-18    303
Freq: D, dtype: int64

In [10]:
stock = pd.Series({'LG': 73800, 'Samsung': 71200, 'Kakao': 106500})
stock

LG          73800
Samsung     71200
Kakao      106500
dtype: int64

In [11]:
#stock.sort_values()
#stock.sort_index()
#stock.sort_values(ascending=False)
#stock.sort_index(ascending=False)

In [12]:
print(stock.where(stock<100000))

LG         73800.0
Samsung    71200.0
Kakao          NaN
dtype: float64


In [13]:
print(stock.where(stock==stock.min()))

LG             NaN
Samsung    71200.0
Kakao          NaN
dtype: float64


In [14]:
changes = pd.Series({'Kakao': 1500, 'LG': 1200, 'SK': -1500})

In [15]:
print(stock, '\n'); print(changes)

LG          73800
Samsung     71200
Kakao      106500
dtype: int64 

Kakao    1500
LG       1200
SK      -1500
dtype: int64


In [16]:
# Series 연산
print(stock.add(changes))
print()
print(stock.add(changes, fill_value=0).astype('int'))

Kakao      108000.0
LG          75000.0
SK              NaN
Samsung         NaN
dtype: float64

Kakao      108000
LG          75000
SK          -1500
Samsung     71200
dtype: int32


In [17]:
#name
stock.name = 'price'   # dataframe 내 column의 제목
stock.index.name = 'market'
stock

market
LG          73800
Samsung     71200
Kakao      106500
Name: price, dtype: int64

In [18]:
pd.DataFrame(stock)

price
market         
LG        73800
Samsung   71200
Kakao    106500

In [19]:
stock['SK']=122000
stock

market
LG          73800
Samsung     71200
Kakao      106500
SK         122000
Name: price, dtype: int64

In [20]:
stock.append(pd.Series({'Naver':345000}))
#stock

C:\Users\alstj\AppData\Local\Temp\ipykernel_17668\2382650702.py:1: FutureWarning: The series.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  stock.append(pd.Series({'Naver':345000}))


LG          73800
Samsung     71200
Kakao      106500
SK         122000
Naver      345000
dtype: int64

In [21]:
del stock['SK']
stock

market
LG          73800
Samsung     71200
Kakao      106500
Name: price, dtype: int64

In [22]:
stock.drop(['LG'])
#stock

market
Samsung     71200
Kakao      106500
Name: price, dtype: int64

In [23]:
stock['SK']=122000
stock
#stock.apply(float)
#stock.apply(lambda x: x/stock.sum())
#stock.apply(lambda x: x**2)

market
LG          73800
Samsung     71200
Kakao      106500
SK         122000
Name: price, dtype: int64

# DataFrame

In [24]:
# DataFrame 생성
a = pd.DataFrame([[10,20,30], [40,50,60],[70,80,90]])
print(a)
print(type(a))
print(len(a))
a

    0   1   2
0  10  20  30
1  40  50  60
2  70  80  90
<class 'pandas.core.frame.DataFrame'>
3


0   1   2
0  10  20  30
1  40  50  60
2  70  80  90

In [25]:
# DataFrame columns, index
data = [[10,20,30], [40,50,60],[70,80,90]]
a = pd.DataFrame(data, columns=['1차','2차','3차'], index = ['One', 'Two', 'Three'])
a

1차  2차  3차
One    10  20  30
Two    40  50  60
Three  70  80  90

In [26]:
print(a.index)    # row 명
print(a.columns)    # columns 명
print(a.values)    # values 값

Index(['One', 'Two', 'Three'], dtype='object')
Index(['1차', '2차', '3차'], dtype='object')
[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [27]:
# yfinance
# yahoo finance에서 주식 데이터를 받아올 수 있는 모듈
tsla = yf.download('TSLA')
aapl = yf.download('AAPL')

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed


In [82]:
tsla.tail()

Open        High         Low       Close   Adj Close  \
Date                                                                     
2023-03-08  185.039993  186.500000  180.000000  182.000000  182.000000   
2023-03-09  180.250000  185.179993  172.509995  172.919998  172.919998   
2023-03-10  175.130005  178.289993  168.440002  173.440002  173.440002   
2023-03-13  167.460007  177.350006  163.910004  174.479996  174.479996   
2023-03-14  177.309998  183.800003  177.139999  183.259995  183.259995   

               Volume  
Date                   
2023-03-08  151897800  
2023-03-09  170023800  
2023-03-10  191007900  
2023-03-13  167790300  
2023-03-14  143430400

In [83]:
aapl.tail()

Open        High         Low       Close   Adj Close  \
Date                                                                     
2023-03-08  152.809998  153.470001  151.830002  152.869995  152.869995   
2023-03-09  153.559998  154.539993  150.229996  150.589996  150.589996   
2023-03-10  150.210007  150.940002  147.610001  148.500000  148.500000   
2023-03-13  147.809998  153.139999  147.699997  150.470001  150.470001   
2023-03-14  151.279999  153.399994  150.100006  152.589996  152.589996   

              Volume  
Date                  
2023-03-08  47204800  
2023-03-09  53833600  
2023-03-10  68524400  
2023-03-13  84457100  
2023-03-14  73628400

1. 특정 열 값을 추출: 인덱싱 또는 속성
 - 변수[열이름] #지정된 열 추출
 - 변수[[열이름1,열이름2,...]]
 - 변수.속성
 
 
2. 리스트와 유사하게 슬라이싱으로 행 추출 
 - 변수[start:end] #start행부터 end-1행까지 추출
 
 
3. 특정 행을 추출
 - 변수.loc[행이름] #지정된 레이블의 행 추출
 - 변수.loc[ [행이름1,행이름2,..] ] #2개 이상은 리스트로 묶어 지정


4. 특정한 요소 하나만을 선택
 - 변수.loc[ 행이름, 열이름 ]


In [84]:
tsla=tsla.tail()
tsla['Close']    # column 이름으로만 indexing 가능
#tsla['2023-03-08']    # error --> index 이름으로는 indexing 불가능 loc 사용필요

Date
2023-03-08    182.000000
2023-03-09    172.919998
2023-03-10    173.440002
2023-03-13    174.479996
2023-03-14    183.259995
Name: Close, dtype: float64

In [85]:
tsla.Close

Date
2023-03-08    182.000000
2023-03-09    172.919998
2023-03-10    173.440002
2023-03-13    174.479996
2023-03-14    183.259995
Name: Close, dtype: float64

In [86]:
print(type(tsla['Close']))

<class 'pandas.core.series.Series'>


In [87]:
tsla[['Open','Close']]

Open       Close
Date                              
2023-03-08  185.039993  182.000000
2023-03-09  180.250000  172.919998
2023-03-10  175.130005  173.440002
2023-03-13  167.460007  174.479996
2023-03-14  177.309998  183.259995

In [88]:
tsla.loc['2023-03-14']

Open         1.773100e+02
High         1.838000e+02
Low          1.771400e+02
Close        1.832600e+02
Adj Close    1.832600e+02
Volume       1.434304e+08
Name: 2023-03-14 00:00:00, dtype: float64

In [89]:
tsla.iloc[1]    # 2023-03-09

Open         1.802500e+02
High         1.851800e+02
Low          1.725100e+02
Close        1.729200e+02
Adj Close    1.729200e+02
Volume       1.700238e+08
Name: 2023-03-09 00:00:00, dtype: float64

In [90]:
# slicing
tsla.loc['2023-03-08':'2023-03-14':2, 'Open':'Close']
#tsla.iloc[0:3,0:3]    # 2023-03-08 ~ 2023-03-10

Open        High         Low       Close
Date                                                      
2023-03-08  185.039993  186.500000  180.000000  182.000000
2023-03-10  175.130005  178.289993  168.440002  173.440002
2023-03-14  177.309998  183.800003  177.139999  183.259995

In [91]:
tsla.reindex(columns=['Open','Close','Adj Close','High','Low','Volume'])

Open       Close   Adj Close        High         Low  \
Date                                                                     
2023-03-08  185.039993  182.000000  182.000000  186.500000  180.000000   
2023-03-09  180.250000  172.919998  172.919998  185.179993  172.509995   
2023-03-10  175.130005  173.440002  173.440002  178.289993  168.440002   
2023-03-13  167.460007  174.479996  174.479996  177.350006  163.910004   
2023-03-14  177.309998  183.259995  183.259995  183.800003  177.139999   

               Volume  
Date                   
2023-03-08  151897800  
2023-03-09  170023800  
2023-03-10  191007900  
2023-03-13  167790300  
2023-03-14  143430400

In [92]:
tsla.rename(columns={'Open':'open'})

open        High         Low       Close   Adj Close  \
Date                                                                     
2023-03-08  185.039993  186.500000  180.000000  182.000000  182.000000   
2023-03-09  180.250000  185.179993  172.509995  172.919998  172.919998   
2023-03-10  175.130005  178.289993  168.440002  173.440002  173.440002   
2023-03-13  167.460007  177.350006  163.910004  174.479996  174.479996   
2023-03-14  177.309998  183.800003  177.139999  183.259995  183.259995   

               Volume  
Date                   
2023-03-08  151897800  
2023-03-09  170023800  
2023-03-10  191007900  
2023-03-13  167790300  
2023-03-14  143430400

In [93]:
#tsla.rename(index={'2023-03-14':'Yesterday'})  --> Error

In [94]:
print(type(tsla.index))

<class 'pandas.core.indexes.datetimes.DatetimeIndex'>


In [95]:
Tsla=tsla.rename(index=lambda x: x.strftime('%Y-%m-%d'))

In [97]:
# Tsla.rename(index={'2023-03-14':'Yesertday'}), inplace=True)
Tsla = Tsla.rename(index={'2023-03-14':'Yesterday'}) # inplace = True를 사용한 것과 같다
Tsla

Open        High         Low       Close   Adj Close  \
Date                                                                     
2023-03-08  185.039993  186.500000  180.000000  182.000000  182.000000   
2023-03-09  180.250000  185.179993  172.509995  172.919998  172.919998   
2023-03-10  175.130005  178.289993  168.440002  173.440002  173.440002   
2023-03-13  167.460007  177.350006  163.910004  174.479996  174.479996   
Yesterday   177.309998  183.800003  177.139999  183.259995  183.259995   

               Volume  
Date                   
2023-03-08  151897800  
2023-03-09  170023800  
2023-03-10  191007900  
2023-03-13  167790300  
Yesterday   143430400

In [98]:
# index 추가
Tsla.loc['Tomorrow']=[304.829987, 310.119995, 310.720001, 310.750000, 310.750000, 54613900]
Tsla

Open        High         Low       Close   Adj Close  \
Date                                                                     
2023-03-08  185.039993  186.500000  180.000000  182.000000  182.000000   
2023-03-09  180.250000  185.179993  172.509995  172.919998  172.919998   
2023-03-10  175.130005  178.289993  168.440002  173.440002  173.440002   
2023-03-13  167.460007  177.350006  163.910004  174.479996  174.479996   
Yesterday   177.309998  183.800003  177.139999  183.259995  183.259995   
Tomorrow    304.829987  310.119995  310.720001  310.750000  310.750000   

                 Volume  
Date                     
2023-03-08  151897800.0  
2023-03-09  170023800.0  
2023-03-10  191007900.0  
2023-03-13  167790300.0  
Yesterday   143430400.0  
Tomorrow     54613900.0

In [99]:
# index 및 column 삭제
# del Tsla['Adj Close']
Tsla.drop(['Yesterday'], axis=0, inplace = True)
Tsla.drop(['Adj Close'], axis=1, inplace = True)
Tsla

Open        High         Low       Close       Volume
Date                                                                   
2023-03-08  185.039993  186.500000  180.000000  182.000000  151897800.0
2023-03-09  180.250000  185.179993  172.509995  172.919998  170023800.0
2023-03-10  175.130005  178.289993  168.440002  173.440002  191007900.0
2023-03-13  167.460007  177.350006  163.910004  174.479996  167790300.0
Tomorrow    304.829987  310.119995  310.720001  310.750000   54613900.0

In [100]:
# list 사용해서 DataFrame 생성
names = ['Amy', 'Bob', 'Cindy', 'James']
score = [13,45,98,71]
data_list = list(zip(names,score))
# data_list
lecture = pd.DataFrame(data = data_list, columns = ['Names', 'Score'])

In [101]:
lecture

Names  Score
0    Amy     13
1    Bob     45
2  Cindy     98
3  James     71

In [102]:
lecture.set_index(['Names'])

Score
Names       
Amy       13
Bob       45
Cindy     98
James     71

In [103]:
# 정렬
lecture.sort_values(by='Score')
lecture.sort_values(by='Score',ascending=False)
lecture.sort_index()    # index
lecture.sort_index(axis=1, ascending=False)    # column명 내림차순

Score  Names
0     13    Amy
1     45    Bob
2     98  Cindy
3     71  James

In [104]:
lecture.index.name='INDEX'
lecture.columns.name='COLUMNS'
lecture

COLUMNS  Names  Score
INDEX                
0          Amy     13
1          Bob     45
2        Cindy     98
3        James     71

In [105]:
lecture.T

INDEX      0    1      2      3
COLUMNS                        
Names    Amy  Bob  Cindy  James
Score     13   45     98     71

In [106]:
stock = pd.Series({'LG': 73800, 'Samsung': 71200, 'Kakao': 106500})
stock

LG          73800
Samsung     71200
Kakao      106500
dtype: int64

In [107]:
stock1=pd.DataFrame(stock)
stock1

0
LG        73800
Samsung   71200
Kakao    106500

In [108]:
stock1.where(stock1<100000)

0
LG       73800.0
Samsung  71200.0
Kakao        NaN

In [109]:
stock1.where(stock1==stock1.min())

0
LG           NaN
Samsung  71200.0
Kakao        NaN

In [111]:
# Series
area = pd.Series({'California':423967, 'Texas':695662, 'New York': 141297, 'Florida': 170312, 'Illinois': 149995})
population = pd.Series({'California':1423967, 'Texas':1695662, 'New York': 1141297, 'Florida': 1170312, 'Illinois': 1149995})
states = pd.DataFrame({'Population': population, 'Area': area , 'Year' : 2022})
states

Population    Area  Year
California     1423967  423967  2022
Texas          1695662  695662  2022
New York       1141297  141297  2022
Florida        1170312  170312  2022
Illinois       1149995  149995  2022

In [112]:
area1 = pd.Series({'Seoul':23967, 'Daegu':15662, 'Busan': 11297})
population1 = pd.Series({'Seoul':423967, 'Daegu':195662, 'Busan': 141297})
states1 = pd.DataFrame({'Population': population1, 'Area': area1})
states1

Population   Area
Seoul      423967  23967
Daegu      195662  15662
Busan      141297  11297

In [113]:
states2=pd.concat([states,states1])
states2

Population    Area    Year
California     1423967  423967  2022.0
Texas          1695662  695662  2022.0
New York       1141297  141297  2022.0
Florida        1170312  170312  2022.0
Illinois       1149995  149995  2022.0
Seoul           423967   23967     NaN
Daegu           195662   15662     NaN
Busan           141297   11297     NaN

In [114]:
states3=pd.concat([states, states1], axis=1)
states3

Population      Area    Year  Population     Area
California   1423967.0  423967.0  2022.0         NaN      NaN
Texas        1695662.0  695662.0  2022.0         NaN      NaN
New York     1141297.0  141297.0  2022.0         NaN      NaN
Florida      1170312.0  170312.0  2022.0         NaN      NaN
Illinois     1149995.0  149995.0  2022.0         NaN      NaN
Seoul              NaN       NaN     NaN    423967.0  23967.0
Daegu              NaN       NaN     NaN    195662.0  15662.0
Busan              NaN       NaN     NaN    141297.0  11297.0

In [115]:
states3.isnull()

Population   Area   Year  Population   Area
California       False  False  False        True   True
Texas            False  False  False        True   True
New York         False  False  False        True   True
Florida          False  False  False        True   True
Illinois         False  False  False        True   True
Seoul             True   True   True       False  False
Daegu             True   True   True       False  False
Busan             True   True   True       False  False

In [116]:
states3.fillna(0)

Population      Area    Year  Population     Area
California   1423967.0  423967.0  2022.0         0.0      0.0
Texas        1695662.0  695662.0  2022.0         0.0      0.0
New York     1141297.0  141297.0  2022.0         0.0      0.0
Florida      1170312.0  170312.0  2022.0         0.0      0.0
Illinois     1149995.0  149995.0  2022.0         0.0      0.0
Seoul              0.0       0.0     0.0    423967.0  23967.0
Daegu              0.0       0.0     0.0    195662.0  15662.0
Busan              0.0       0.0     0.0    141297.0  11297.0

In [117]:
states2.dropna()

Population    Area    Year
California     1423967  423967  2022.0
Texas          1695662  695662  2022.0
New York       1141297  141297  2022.0
Florida        1170312  170312  2022.0
Illinois       1149995  149995  2022.0

In [118]:
# dataframe 파일 저장
states.to_csv('dataframe.txt', sep = ' ')
# 파일 dataframe으로 불러오기
file = pd.read_csv('dataframe.txt', encoding = '', index_col = 0)
# index_col=0 --> column의 0번째 목록을 index로 취급 

In [119]:
file

Empty DataFrame
Columns: []
Index: [California 1423967 423967 2022, Texas 1695662 695662 2022, New York 1141297 141297 2022, Florida 1170312 170312 2022, Illinois 1149995 149995 2022]